title: The Coder Bear
description: Sharing my notes and logs on technical subjects from EAIs to AI
author: Mahieddine Cherif
github: https://github.com/mahieddine
about: I am a Senior BizTalk Consultant. I share here my notes and logs on technical subjects from EAIs to AI.
disqus_shortname: the-coder-bear
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/mahieddinech"
    - icon: fa-twitter
      link: "https://twitter.com/mahieddinech"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/mahieddinecherif/"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/1543306/mahieddine?tab=profile"
    - icon: fa-github
      link: "https://github.com/mahieddine"

share:
  twitter_username: mahieddinech
  fb_appid: 1749788565247320

urls:
    - text: EAI (BizTalk, Azure Services...)
      url: /category/eai
    - text: .NET
      url: /category/dotnet
    - text: AI
      url: /category/ai
    - text: Experiments
      url: /category/experiments

url: "https://mahieddine.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
